#!/bin/bash

# Script generated by GitHub Copilot. Please review the script before executing.

# Check if all arguments are provided
if [ "$#" -ne 4 ]; then
    echo "Usage: $0 <AZURE_OPENAI_NAME> <RESOURCE_GROUP_NAME> <SESSION_POOL_NAME> <SUBSCRIPTION_NAME>"
    exit 1
fi

AZURE_OPENAI_NAME=$1
RESOURCE_GROUP_NAME=$2
SESSION_POOL_NAME=$3
SUBSCRIPTION_NAME=$4

# Prompt user for confirmation
echo "############################################################"
echo "#     This script was generated by GitHub Copilot.         #"
echo "#     Please review the script before executing.           #"
echo "############################################################"
read -p "Do you want to proceed with the script execution? (Y/y/yes to proceed): " confirmation

if [[ "$confirmation" =~ ^([yY][eE][sS]|[yY])$ ]]; then
    az account set --subscription $SUBSCRIPTION_NAME

    alias=$(az account show --query user.name --output tsv)
    azureopenai_scope=$(az cognitiveservices account show --name $AZURE_OPENAI_NAME --resource-group $RESOURCE_GROUP_NAME --query id --output tsv)
    az role assignment create --role "Cognitive Services OpenAI User" --assignee $alias --scope $azureopenai_scope

    session_pool_scope=$(az containerapp sessionpool show --name $SESSION_POOL_NAME --resource-group $RESOURCE_GROUP_NAME --query id --output tsv)
    az role assignment create \
        --role "Azure ContainerApps Session Executor" \
        --assignee $alias \
        --scope $session_pool_scope
else
    echo "Script execution aborted."
    exit 0
fi