#!/bin/bash

# This script was generated by GitHub Copilot

# Function to ask for user confirmation
confirm() {
    read -p "Are you sure you want to proceed? (Y/y/yes): " choice
    case "$choice" in 
        Y|y|yes ) echo "Proceeding...";;
        * ) echo "Operation cancelled."; exit 1;;
    esac
}

# Check if the required arguments are provided
if [ "$#" -ne 4 ]; then
    echo "Usage: $0 <subscription> <AZURE_OPENAI_NAME> <RESOURCE_GROUP_NAME> <SESSION_POOL_NAME>"
    exit 1
fi

subscription=$1
AZURE_OPENAI_NAME=$2
RESOURCE_GROUP_NAME=$3
SESSION_POOL_NAME=$4

# Banner
echo "##################################################"
echo "# This script was generated using GitHub Copilot #"
echo "##################################################"
# Ask for confirmation
confirm

# Set the subscription
az account set --subscription $subscription
echo " - Successfully set the subscription to $subscription"

echo 
echo " Add the result of the following commands to .env file in src/app folder"

# Show the cognitive services account endpoint
az cognitiveservices account show \
    --name $AZURE_OPENAI_NAME \
    --resource-group $RESOURCE_GROUP_NAME \
    --query properties.endpoint \
    --output tsv

# Show the container app session pool management endpoint
az containerapp sessionpool show \
    --name $SESSION_POOL_NAME \
    --resource-group $RESOURCE_GROUP_NAME \
    --query properties.poolManagementEndpoint \
    --output tsv
